# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'achorda' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for achorda

  target 'achordaTests' do
    inherit! :search_paths
    # Pods for testing
  end

	
  pod 'Alamofire', '~> 4.3'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'achordaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
